ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_LG_OIS)   += msm_ois.o msm_ois_i2c.o lgit_ois_old.o ff_ois.o lgit_ois.o
#obj-$(CONFIG_LG_OIS)   += msm_ois.o msm_ois_i2c.o ff_ois.o lgit_ois.o K7_ois_init.o